### ISSUE TITLE
unable to pass s3 file location in fastdup.run()

### ISSUE THREAD

**Issue by sameersharma00747** [visualdatabase/fastdup#13]
Hi, I tried passing s3 folder location while running fastdup.run(). It is throwing this error  "Failed to find input dir"

**Comment by dbickson** [comment]
Hi @sameersharma00747 thanks for sharing this bug. We have just released v 0.134 let us know if this works for you?

**Comment by sameersharma00747** [comment]
Still getting the same error. Is passing S3 URI working at your end? Is there any specific format in which I should pass it?

This is how I am running the command:
fastdup.run(input_dir='s3://bucket_name/sameer/', work_dir='out')

**Comment by dbickson** [comment]
Hi @sameersharma00747 can you make sure you upgraded using 
`python3.8 -m pip install -U --force-reinstall fastdup` ?
Run with verbose=1 and send us the output.

**Comment by sameersharma00747** [comment]
I am running this in a python notebook on databricks and the kernel is gettin killed after I do fastdup.run() with the s3 folder path.

You can have a look at the verbose below in the image:

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/105480080/188262985-17167df8-c569-4116-b1f7-46f1b60bf41f.png">

**Comment by dbickson** [comment]
Fixed on v. 0.137, closing
